### ISSUE TITLE
Transfer IPXACT-Schema from UnofficialRepos to edaa-org

### ISSUE THREAD

**Issue by umarcor** [edaa-org/pyEDAA.IPXACT#8]
Since IPXACT-Schema is a submodule of this repository, it would be sensible to transfer it from [UnofficialRepos/IPXACT-Schema](https://github.com/UnofficialRepos/IPXACT-Schema) to this organisation.

**Comment by Paebbels** [comment]
Oh, Maybe we need to update the `.gitmodules` file, right?
